"""new fields finish data in eo model

Revision ID: 03c2444ba998
Revises: 5bffe5d49831
Create Date: 2022-06-30 07:47:42.341253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c2444ba998'
down_revision = '5bffe5d49831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_finish_date_sap', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('operation_finish_date_calc', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('operation_finish_date_sap_upd', sa.DateTime(), nullable=True))
        batch_op.drop_column('age_date_31122027')
        batch_op.drop_column('age_31122022_calc_operation_status')
        batch_op.drop_column('age_31122023_calc_operation_status')
        batch_op.drop_column('age_31122022')
        batch_op.drop_column('age_31122025_calc_operation_status')
        batch_op.drop_column('age_31122027_calc_operation_status')
        batch_op.drop_column('age_31122026_calc_operation_status')
        batch_op.drop_column('age_date_31122026')
        batch_op.drop_column('age_31122026')
        batch_op.drop_column('age_31122023')
        batch_op.drop_column('age_31122024')
        batch_op.drop_column('age_31122025')
        batch_op.drop_column('age_date_31122025')
        batch_op.drop_column('age_date_31122023')
        batch_op.drop_column('age_31122027')
        batch_op.drop_column('age_date_31122022')
        batch_op.drop_column('age_31122024_calc_operation_status')
        batch_op.drop_column('age_date_31122024')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_date_31122024', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age_31122024_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122022', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age_31122027', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122023', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122025', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age_31122025', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_31122024', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_31122023', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_31122026', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122026', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age_31122026_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_31122027_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_31122025_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_31122022', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('age_31122023_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_31122022_calc_operation_status', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122027', sa.DATETIME(), nullable=True))
        batch_op.drop_column('operation_finish_date_sap_upd')
        batch_op.drop_column('operation_finish_date_calc')
        batch_op.drop_column('operation_finish_date_sap')

    # ### end Alembic commands ###
