"""models

Revision ID: 07017e254730
Revises: 6bf75fc7cff4
Create Date: 2022-07-08 14:34:18.999350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07017e254730'
down_revision = '6bf75fc7cff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_tehniki', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('marka_oborudovania', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.drop_column('marka_oborudovania')
        batch_op.drop_column('type_tehniki')

    # ### end Alembic commands ###
