"""init

Revision ID: 0c0610c7ddc7
Revises: 1b638ea3c377
Create Date: 2022-06-20 15:10:45.927362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0610c7ddc7'
down_revision = '1b638ea3c377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_31122023', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122023', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age_31122023_calc_operation_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('age_31122023_calc_operation_status')
        batch_op.drop_column('age_date_31122023')
        batch_op.drop_column('age_31122023')

    # ### end Alembic commands ###
