"""sap model name

Revision ID: 15753ca6d610
Revises: 9dbc2c1cb28b
Create Date: 2022-06-17 07:44:32.675137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15753ca6d610'
down_revision = '9dbc2c1cb28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_gar_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sap_model_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('sap_model_name')
        batch_op.drop_column('sap_gar_no')

    # ### end Alembic commands ###
