"""sap finish data

Revision ID: 1b298da3678a
Revises: f80517ab8832
Create Date: 2022-06-16 09:18:22.437475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b298da3678a'
down_revision = 'f80517ab8832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_planned_finish_operarion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('sap_planned_finish_operarion_date')

    # ### end Alembic commands ###
