"""migrate

Revision ID: 2c820c121a96
Revises: 03c2444ba998
Create Date: 2022-06-30 11:03:01.865724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c820c121a96'
down_revision = '03c2444ba998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('operation_finish_date_sap')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_finish_date_sap', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
