"""init

Revision ID: 35856df5297b
Revises: 8524471dff8e
Create Date: 2022-06-21 07:12:45.852678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35856df5297b'
down_revision = '8524471dff8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_calendar_operation_status_DB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eo_code', sa.String(), nullable=True),
    sa.Column('july_2022', sa.Integer(), nullable=True),
    sa.Column('august_2022', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eo_code'], ['eo_DB.eo_code'], name=op.f('fk_eo_calendar_operation_status_DB_eo_code_eo_DB')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eo_calendar_operation_status_DB'))
    )
    op.drop_table('eo_calendar_opearation_status_DB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_calendar_opearation_status_DB',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eo_code', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['eo_code'], ['eo_DB.eo_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eo_calendar_operation_status_DB')
    # ### end Alembic commands ###
