"""maker field

Revision ID: 5bffe5d49831
Revises: 9957c4847e9f
Create Date: 2022-06-27 15:05:04.283752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bffe5d49831'
down_revision = '9957c4847e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_operation_status_calc_temp')
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maker', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('maker')

    op.create_table('calendar_operation_status_calc_temp',
    sa.Column('be_code', sa.REAL(), nullable=True),
    sa.Column('be_description', sa.TEXT(), nullable=True),
    sa.Column('eo_class_code', sa.TEXT(), nullable=True),
    sa.Column('eo_class_description', sa.TEXT(), nullable=True),
    sa.Column('eo_model_name', sa.TEXT(), nullable=True),
    sa.Column('teh_mesto', sa.TEXT(), nullable=True),
    sa.Column('gar_no', sa.TEXT(), nullable=True),
    sa.Column('eo_code', sa.TEXT(), nullable=True),
    sa.Column('head_type', sa.TEXT(), nullable=True),
    sa.Column('operation_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_period_years', sa.REAL(), nullable=True),
    sa.Column('expected_operation_finish_date', sa.TEXT(), nullable=True),
    sa.Column('sap_planned_finish_operation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_status_code', sa.TEXT(), nullable=True),
    sa.Column('expected_operation_status_code_date', sa.TEXT(), nullable=True),
    sa.Column('sap_system_status', sa.TEXT(), nullable=True),
    sa.Column('sap_user_status', sa.TEXT(), nullable=True),
    sa.Column('reported_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reported_operation_status', sa.TEXT(), nullable=True),
    sa.Column('evaluated_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.REAL(), nullable=True)
    )
    # ### end Alembic commands ###
