"""init

Revision ID: 691a1ecbf0d7
Revises: 9dcc89ac414b
Create Date: 2022-06-15 06:31:41.987640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691a1ecbf0d7'
down_revision = '9dcc89ac414b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_statusDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_status_code', sa.String(), nullable=True),
    sa.Column('operation_status_description', sa.String(), nullable=True),
    sa.Column('sap_operation_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_statusDB'))
    )
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_operation_period_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_operation_status_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reported_operation_status_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reported_operation_status_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sap_system_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sap_user_status', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_eo_DB_expected_operation_status_code_operation_statusDB'), 'operation_statusDB', ['expected_operation_status_code'], ['operation_status_code'])
        batch_op.create_foreign_key(batch_op.f('fk_eo_DB_reported_operation_status_code_operation_statusDB'), 'operation_statusDB', ['reported_operation_status_code'], ['operation_status_code'])
        batch_op.drop_column('operation_status_date')
        batch_op.drop_column('operation_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('operation_status_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_eo_DB_reported_operation_status_code_operation_statusDB'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_eo_DB_expected_operation_status_code_operation_statusDB'), type_='foreignkey')
        batch_op.drop_column('sap_user_status')
        batch_op.drop_column('sap_system_status')
        batch_op.drop_column('reported_operation_status_date')
        batch_op.drop_column('reported_operation_status_code')
        batch_op.drop_column('expected_operation_status_code')
        batch_op.drop_column('expected_operation_period_years')

    op.drop_table('operation_statusDB')
    # ### end Alembic commands ###
