"""age_calc

Revision ID: 6bbe5816680f
Revises: f91da31ec306
Create Date: 2022-06-17 14:16:24.284876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbe5816680f'
down_revision = 'f91da31ec306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_calc_operation_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('age_calc_operation_status')

    # ### end Alembic commands ###
