"""init

Revision ID: 8524471dff8e
Revises: f2eaae1d7ad5
Create Date: 2022-06-21 06:05:42.936260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8524471dff8e'
down_revision = 'f2eaae1d7ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eo_calendar_opearation_status_DB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eo_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['eo_code'], ['eo_DB.eo_code'], name=op.f('fk_eo_calendar_opearation_status_DB_eo_code_eo_DB')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eo_calendar_opearation_status_DB'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eo_calendar_opearation_status_DB')
    # ### end Alembic commands ###
