"""init

Revision ID: 9957c4847e9f
Revises: b3bc3190d2ce
Create Date: 2022-06-23 07:43:20.964061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9957c4847e9f'
down_revision = 'b3bc3190d2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_operation_status_calc_temp')
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2028_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2028_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2028_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2028_out', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2029_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2029_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2029_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2029_out', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2030_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2030_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2030_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2030_out', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2031_qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2031_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2031_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_2031_out', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.drop_column('year_2031_out')
        batch_op.drop_column('year_2031_in')
        batch_op.drop_column('year_2031_age')
        batch_op.drop_column('year_2031_qty')
        batch_op.drop_column('year_2030_out')
        batch_op.drop_column('year_2030_in')
        batch_op.drop_column('year_2030_age')
        batch_op.drop_column('year_2030_qty')
        batch_op.drop_column('year_2029_out')
        batch_op.drop_column('year_2029_in')
        batch_op.drop_column('year_2029_age')
        batch_op.drop_column('year_2029_qty')
        batch_op.drop_column('year_2028_out')
        batch_op.drop_column('year_2028_in')
        batch_op.drop_column('year_2028_age')
        batch_op.drop_column('year_2028_qty')

    op.create_table('calendar_operation_status_calc_temp',
    sa.Column('be_code', sa.REAL(), nullable=True),
    sa.Column('be_description', sa.TEXT(), nullable=True),
    sa.Column('eo_class_code', sa.TEXT(), nullable=True),
    sa.Column('eo_class_description', sa.TEXT(), nullable=True),
    sa.Column('eo_model_name', sa.TEXT(), nullable=True),
    sa.Column('teh_mesto', sa.TEXT(), nullable=True),
    sa.Column('gar_no', sa.TEXT(), nullable=True),
    sa.Column('eo_code', sa.TEXT(), nullable=True),
    sa.Column('head_type', sa.TEXT(), nullable=True),
    sa.Column('operation_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_period_years', sa.INTEGER(), nullable=True),
    sa.Column('expected_operation_finish_date', sa.TEXT(), nullable=True),
    sa.Column('sap_planned_finish_operation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_status_code', sa.TEXT(), nullable=True),
    sa.Column('expected_operation_status_code_date', sa.TEXT(), nullable=True),
    sa.Column('sap_system_status', sa.TEXT(), nullable=True),
    sa.Column('sap_user_status', sa.TEXT(), nullable=True),
    sa.Column('reported_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reported_operation_status', sa.TEXT(), nullable=True),
    sa.Column('evaluated_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
