"""nullable eo-code false

Revision ID: 9dbc2c1cb28b
Revises: bbaf9c72bf7d
Create Date: 2022-06-16 15:54:06.459594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbc2c1cb28b'
down_revision = 'bbaf9c72bf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.alter_column('eo_code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.alter_column('eo_code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
