"""field reported_operation_status

Revision ID: 9e9348366a3b
Revises: b4ab4a1ca159
Create Date: 2022-06-15 13:57:52.499958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9348366a3b'
down_revision = 'b4ab4a1ca159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_operation_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('reported_operation_status')

    # ### end Alembic commands ###
