"""init

Revision ID: b3bc3190d2ce
Revises: f50958947801
Create Date: 2022-06-23 07:05:40.550487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bc3190d2ce'
down_revision = 'f50958947801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_operation_status_calc_temp')
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eo_category_spec', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.drop_column('eo_category_spec')

    op.create_table('calendar_operation_status_calc_temp',
    sa.Column('be_code', sa.REAL(), nullable=True),
    sa.Column('be_description', sa.TEXT(), nullable=True),
    sa.Column('eo_class_code', sa.TEXT(), nullable=True),
    sa.Column('eo_class_description', sa.TEXT(), nullable=True),
    sa.Column('eo_model_name', sa.TEXT(), nullable=True),
    sa.Column('teh_mesto', sa.TEXT(), nullable=True),
    sa.Column('gar_no', sa.TEXT(), nullable=True),
    sa.Column('eo_code', sa.TEXT(), nullable=True),
    sa.Column('head_type', sa.TEXT(), nullable=True),
    sa.Column('operation_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_period_years', sa.INTEGER(), nullable=True),
    sa.Column('expected_operation_finish_date', sa.TEXT(), nullable=True),
    sa.Column('sap_planned_finish_operation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_status_code', sa.TEXT(), nullable=True),
    sa.Column('expected_operation_status_code_date', sa.TEXT(), nullable=True),
    sa.Column('sap_system_status', sa.TEXT(), nullable=True),
    sa.Column('sap_user_status', sa.TEXT(), nullable=True),
    sa.Column('reported_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reported_operation_status', sa.TEXT(), nullable=True),
    sa.Column('evaluated_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
