"""expected status date field

Revision ID: b4ab4a1ca159
Revises: 691a1ecbf0d7
Create Date: 2022-06-15 09:33:33.614605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ab4a1ca159'
down_revision = '691a1ecbf0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_operation_status_code_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('expected_operation_status_code_date')

    # ### end Alembic commands ###
