"""init

Revision ID: bbaf9c72bf7d
Revises: 1b298da3678a
Create Date: 2022-06-16 11:26:23.290640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaf9c72bf7d'
down_revision = '1b298da3678a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_planned_finish_operation_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('sap_planned_finish_operarion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sap_planned_finish_operarion_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sap_planned_finish_operation_date')

    # ### end Alembic commands ###
