"""init

Revision ID: d31de5940c35
Revises: 318183f18738
Create Date: 2022-06-22 07:00:01.908464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31de5940c35'
down_revision = '318183f18738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_table', schema=None) as batch_op:
        batch_op.drop_index('ix_temporary_table_index')

    op.drop_table('temporary_table')
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('july_2022_age', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.drop_column('july_2022_age')

    op.create_table('temporary_table',
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('be_code', sa.REAL(), nullable=True),
    sa.Column('be_description', sa.TEXT(), nullable=True),
    sa.Column('eo_class_code', sa.TEXT(), nullable=True),
    sa.Column('eo_class_description', sa.TEXT(), nullable=True),
    sa.Column('eo_model_name', sa.TEXT(), nullable=True),
    sa.Column('teh_mesto', sa.TEXT(), nullable=True),
    sa.Column('gar_no', sa.TEXT(), nullable=True),
    sa.Column('eo_code', sa.TEXT(), nullable=True),
    sa.Column('head_type', sa.TEXT(), nullable=True),
    sa.Column('operation_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_period_years', sa.INTEGER(), nullable=True),
    sa.Column('expected_operation_finish_date', sa.TEXT(), nullable=True),
    sa.Column('sap_planned_finish_operation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_status_code', sa.TEXT(), nullable=True),
    sa.Column('expected_operation_status_code_date', sa.TEXT(), nullable=True),
    sa.Column('sap_system_status', sa.TEXT(), nullable=True),
    sa.Column('sap_user_status', sa.TEXT(), nullable=True),
    sa.Column('reported_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reported_operation_status', sa.TEXT(), nullable=True),
    sa.Column('evaluated_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    with op.batch_alter_table('temporary_table', schema=None) as batch_op:
        batch_op.create_index('ix_temporary_table_index', ['index'], unique=False)

    # ### end Alembic commands ###
