"""migrate

Revision ID: dc1e90624834
Revises: 4bd918731789
Create Date: 2022-07-05 08:43:46.145447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1e90624834'
down_revision = '4bd918731789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_finish_date_conflict', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('operation_finish_date_conflict')

    # ### end Alembic commands ###
