"""init

Revision ID: e967dd086292
Revises: e256eac487aa
Create Date: 2022-07-19 13:14:51.343028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e967dd086292'
down_revision = 'e256eac487aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models_DB', schema=None) as batch_op:
        batch_op.drop_column('cost_center')

    # ### end Alembic commands ###
