"""init

Revision ID: f2eaae1d7ad5
Revises: 0c0610c7ddc7
Create Date: 2022-06-20 15:29:25.968248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2eaae1d7ad5'
down_revision = '0c0610c7ddc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_31122024', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122024', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age_31122024_calc_operation_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_31122025', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122025', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age_31122025_calc_operation_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_31122026', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122026', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age_31122026_calc_operation_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_31122027', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date_31122027', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('age_31122027_calc_operation_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('age_31122027_calc_operation_status')
        batch_op.drop_column('age_date_31122027')
        batch_op.drop_column('age_31122027')
        batch_op.drop_column('age_31122026_calc_operation_status')
        batch_op.drop_column('age_date_31122026')
        batch_op.drop_column('age_31122026')
        batch_op.drop_column('age_31122025_calc_operation_status')
        batch_op.drop_column('age_date_31122025')
        batch_op.drop_column('age_31122025')
        batch_op.drop_column('age_31122024_calc_operation_status')
        batch_op.drop_column('age_date_31122024')
        batch_op.drop_column('age_31122024')

    # ### end Alembic commands ###
