"""age columns

Revision ID: f50958947801
Revises: d31de5940c35
Create Date: 2022-06-22 13:25:26.346877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50958947801'
down_revision = 'd31de5940c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_operation_status_calc_temp')
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('august_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sep_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oct_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nov_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dec_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2022_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2023_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2024_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2025_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2026_age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year_2027_age', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_calendar_operation_status_DB', schema=None) as batch_op:
        batch_op.drop_column('year_2027_age')
        batch_op.drop_column('year_2026_age')
        batch_op.drop_column('year_2025_age')
        batch_op.drop_column('year_2024_age')
        batch_op.drop_column('year_2023_age')
        batch_op.drop_column('year_2022_age')
        batch_op.drop_column('dec_2022_age')
        batch_op.drop_column('nov_2022_age')
        batch_op.drop_column('oct_2022_age')
        batch_op.drop_column('sep_2022_age')
        batch_op.drop_column('august_2022_age')

    op.create_table('calendar_operation_status_calc_temp',
    sa.Column('be_code', sa.REAL(), nullable=True),
    sa.Column('be_description', sa.TEXT(), nullable=True),
    sa.Column('eo_class_code', sa.TEXT(), nullable=True),
    sa.Column('eo_class_description', sa.TEXT(), nullable=True),
    sa.Column('eo_model_name', sa.TEXT(), nullable=True),
    sa.Column('teh_mesto', sa.TEXT(), nullable=True),
    sa.Column('gar_no', sa.TEXT(), nullable=True),
    sa.Column('eo_code', sa.TEXT(), nullable=True),
    sa.Column('head_type', sa.TEXT(), nullable=True),
    sa.Column('operation_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_period_years', sa.INTEGER(), nullable=True),
    sa.Column('expected_operation_finish_date', sa.TEXT(), nullable=True),
    sa.Column('sap_planned_finish_operation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('expected_operation_status_code', sa.TEXT(), nullable=True),
    sa.Column('expected_operation_status_code_date', sa.TEXT(), nullable=True),
    sa.Column('sap_system_status', sa.TEXT(), nullable=True),
    sa.Column('sap_user_status', sa.TEXT(), nullable=True),
    sa.Column('reported_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('reported_operation_status', sa.TEXT(), nullable=True),
    sa.Column('evaluated_operation_finish_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
