"""updated log table

Revision ID: f80517ab8832
Revises: fb5ed9fae5e7
Create Date: 2022-06-16 05:47:28.693814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80517ab8832'
down_revision = 'fb5ed9fae5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_eo_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('be_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('be_sender_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('be_email_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_logsDB_log_eo_code_eo_DB'), 'eo_DB', ['log_eo_code'], ['eo_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logsDB', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_logsDB_log_eo_code_eo_DB'), type_='foreignkey')
        batch_op.drop_column('be_email_date')
        batch_op.drop_column('be_sender_email')
        batch_op.drop_column('be_filename')
        batch_op.drop_column('log_eo_code')

    # ### end Alembic commands ###
