"""age

Revision ID: f91da31ec306
Revises: 3972d87653e3
Create Date: 2022-06-17 13:32:52.314825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91da31ec306'
down_revision = '3972d87653e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eo_DB', schema=None) as batch_op:
        batch_op.drop_column('age_date')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
